<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Logs\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\SmartShip.Shared\SmartShip.Shared.csproj" />
    <ProjectReference Include="..\..\Core\SmartShip.Admin.Application\SmartShip.Admin.Application.csproj" />
    <ProjectReference Include="..\..\Core\SmartShip.Admin.Domain\SmartShip.Admin.Domain.csproj" />
  </ItemGroup>

</Project>
