// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartShip.Admin.Infrastructure.Context;

#nullable disable

namespace SmartShip.Admin.Infrastructure.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    partial class AdminDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartShip.Admin.Domain.Entities.DashboardMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveShipments")
                        .HasColumnType("int");

                    b.Property<int>("DeliveredToday")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalCustomers")
                        .HasColumnType("int");

                    b.Property<int>("TotalShipments")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DashboardMetrics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveShipments = 0,
                            DeliveredToday = 0,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalCustomers = 0,
                            TotalShipments = 0
                        });
                });

            modelBuilder.Entity("SmartShip.Admin.Domain.Entities.Hub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hubs");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            City = "Bengaluru",
                            ContactPhone = "9800000003",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Bangalore Hub",
                            State = "Karnataka"
                        },
                        new
                        {
                            Id = 102,
                            City = "Hyderabad",
                            ContactPhone = "9800000004",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Hyderabad Hub",
                            State = "Telangana"
                        },
                        new
                        {
                            Id = 103,
                            City = "Chennai",
                            ContactPhone = "9800000005",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Chennai Hub",
                            State = "Tamil Nadu"
                        },
                        new
                        {
                            Id = 104,
                            City = "Kolkata",
                            ContactPhone = "9800000006",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Kolkata Hub",
                            State = "West Bengal"
                        },
                        new
                        {
                            Id = 105,
                            City = "Jalandhar",
                            ContactPhone = "9800000007",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Jalandhar Hub",
                            State = "Punjab"
                        },
                        new
                        {
                            Id = 106,
                            City = "Lucknow",
                            ContactPhone = "9800000008",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Lucknow Hub",
                            State = "Uttar Pradesh"
                        },
                        new
                        {
                            Id = 107,
                            City = "Pune",
                            ContactPhone = "9800000009",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Pune Hub",
                            State = "Maharashtra"
                        },
                        new
                        {
                            Id = 108,
                            City = "Ahmedabad",
                            ContactPhone = "9800000010",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Ahmedabad Hub",
                            State = "Gujarat"
                        },
                        new
                        {
                            Id = 109,
                            City = "Jaipur",
                            ContactPhone = "9800000011",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Jaipur Hub",
                            State = "Rajasthan"
                        },
                        new
                        {
                            Id = 110,
                            City = "Chandigarh",
                            ContactPhone = "9800000012",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Chandigarh Hub",
                            State = "Chandigarh"
                        },
                        new
                        {
                            Id = 111,
                            City = "Indore",
                            ContactPhone = "9800000013",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Indore Hub",
                            State = "Madhya Pradesh"
                        },
                        new
                        {
                            Id = 112,
                            City = "Nagpur",
                            ContactPhone = "9800000014",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Nagpur Hub",
                            State = "Maharashtra"
                        },
                        new
                        {
                            Id = 113,
                            City = "Patna",
                            ContactPhone = "9800000015",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Patna Hub",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 114,
                            City = "Bhopal",
                            ContactPhone = "9800000016",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Bhopal Hub",
                            State = "Madhya Pradesh"
                        },
                        new
                        {
                            Id = 115,
                            City = "Kochi",
                            ContactPhone = "9800000017",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Kochi Hub",
                            State = "Kerala"
                        },
                        new
                        {
                            Id = 116,
                            City = "Guwahati",
                            ContactPhone = "9800000018",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Guwahati Hub",
                            State = "Assam"
                        },
                        new
                        {
                            Id = 117,
                            City = "Coimbatore",
                            ContactPhone = "9800000019",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Coimbatore Hub",
                            State = "Tamil Nadu"
                        },
                        new
                        {
                            Id = 118,
                            City = "Visakhapatnam",
                            ContactPhone = "9800000020",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Visakhapatnam Hub",
                            State = "Andhra Pradesh"
                        });
                });

            modelBuilder.Entity("SmartShip.Admin.Domain.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
