<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Context\" />
    <Folder Include="Logs\" />
    <Folder Include="Persistence\" />
    <Folder Include="Repository\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\SmartShip.Tracking.Application\SmartShip.Tracking.Application.csproj" />
    <ProjectReference Include="..\..\Core\SmartShip.Tracking.Domain\SmartShip.Tracking.Domain.csproj" />
  </ItemGroup>

</Project>
