<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
	<ItemGroup>
		<Folder Include="Entities\" />
		<Folder Include="Services\" />
		<Folder Include="Repositories\" />
		<Folder Include="Controllers\" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\..\Core\SmartShip.Admin.Application\SmartShip.Admin.Application.csproj" />
	  <ProjectReference Include="..\..\Core\SmartShip.Admin.Domain\SmartShip.Admin.Domain.csproj" />
	  <ProjectReference Include="..\..\Infrastructure\SmartShip.Admin.Infrastructure\SmartShip.Admin.Infrastructure.csproj" />
	  <ProjectReference Include="..\..\Presentation\SmartShip.Admin.API\SmartShip.Admin.API.csproj" />
	</ItemGroup>
</Project>