<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Contollers\" />
    <Folder Include="Middleware\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\SmartShip.Tracking.Application\SmartShip.Tracking.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\SmartShip.Tracking.Infrastructure\SmartShip.Tracking.Infrastructure.csproj" />
  </ItemGroup>

</Project>
