<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\SmartShip.Identity.Application\SmartShip.Identity.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\SmartShip.Identity.Infrastructure\SmartShip.Identity.Infrastructure.csproj" />
  </ItemGroup>

</Project>
